name: Update Haskell Stack dependencies

on:
  schedule:
    - cron: '0 0 * * 0'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-stack:
    permissions:
      contents: write
      pull-requests: write
    name: Update dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Stack
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-no-global: true

      - name: Update stack dependencies
        id: bump-deps
        uses: stevemao/dep-haskell-stack@v2.4.2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message:
            'Automatic update of the Stack resolver'
          title:
            'Update Stack resolver'

### We are not ready for this yet
###      - name: Enable auto-merge for Dependabot PRs
###        if: steps.pr.outputs.pull-request-url
###        run: gh pr merge --auto --merge "$PR_URL"
###        env:
###          PR_URL: ${{steps.pr.outputs.pull-request-url}}
###          GH_TOKEN: ${{ env.GITHUB_TOKEN }}